### ISSUE TITLE
Unrelated spring documentation from reactor netty reference doc

### ISSUE THREAD

**Issue by pderop** [reactor/antora-ui-projectreactor#7]
## Expected Behavior
when you click on the "..." button right after the "Reactor Netty Reference Guide", we should only see projectreactor related documentations.

## Actual Behavior

but currently, you see some spring related documentation that is not related to projectreactor:

![Screenshot 2024-04-03 at 15 19 08](https://github.com/reactor/antora-ui-projectreactor/assets/650758/cfd38190-4619-4b0c-b761-cc80fef6b343)

## Possible Solution

we should only see documentations related to projectreactor (when all sub projects antora docs will be available)

**Comment by oodamien** [comment]
https://github.com/reactor/antora-ui-projectreactor/blob/main/src/helpers/spring-projects.js

External projects are defined in this file.
Can we define a new list?

**Comment by pderop** [comment]
@oodamien, 

The updated list from https://github.com/reactor/antora-ui-projectreactor/blob/main/src/helpers/spring-projects.js seems ok, 
I think we can close this issue.

thanks!
