### ISSUE TITLE
Search unexpected message

### ISSUE THREAD

**Issue by pderop** [reactor/antora-ui-projectreactor#9]
## Expected Behavior

no extra unrelated message should be displayed when clicking on seach button from reactor netty [ref doc](https://projectreactor.io/docs/netty/snapshot/reference/about-doc.html)

## Actual Behavior

When you search, you get an unexpected "Search in all Spring Docs" message:

![Screenshot 2024-04-03 at 15 33 04](https://github.com/reactor/antora-ui-projectreactor/assets/650758/95ab1f5a-f3e4-484f-a5e6-b2950b27613d)

**Comment by oodamien** [comment]
Typo fixed, closed in favor of https://github.com/reactor/antora-ui-projectreactor/issues/12
